import React from "react";
import { Helmet } from "react-helmet";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Game from "../components/Game";

function Home() {
  return (
    <>
      <Helmet>
        <title data-testid="title-label">
          Impossible Chess | Can you beat the best bot in the world?
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@impossiblechess" />
        <meta name="twitter:creator" content="@impossiblechess" />
        <meta property="og:url" content="http://impossiblechess.com" />
        <meta property="og:title" content="Impossible Chess" />
        <meta
          property="og:description"
          content="Can you beat the best bot in the world?"
        />
        <meta property="og:image" content="/impossible-chess-twitter.png" />
      </Helmet>
      <Header />
      <Game />
      <Footer />
    </>
  );
}

export { Home };
