
function About() {
  return (
    <>
      <Head>
        <title>About | Impossible Chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <p>Hello is is the about page</p>
      <Footer />
    </>
  );
}

export {About}