import Head from "next/head";
import Link from "next/link";
import { Chessboard } from "react-chessboard";
import Header from "/components/Header";
import Footer from "/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>About | Impossible Chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Footer />
    </>
  );
}
