import React, { Component } from "react";
import Chessboard from "chessboardjsx";
import Header from "./Header";
import Footer from "./Footer";
import Leaderboard from "./Leaderboard";
import StockFish from "./integrations/Stockfish.js";
import { VscDebugRestart } from "react-icons/vsc";
import { FaRobot } from "react-icons/fa";
import PostGameModal from "./postGameModal";
import Welcome from "./welcome";
import { Helmet } from "react-helmet";
import { Chess } from "chess.js";
import { ToastContainer, toast } from "react-toastify";

class Game extends Component {
  render() {
    return (
      <>
        <Helmet>
          <title>
            Impossible Chess | Can you beat the best bot in the world?
          </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="twitter:card" content="summary" />
          <meta name="twitter:site" content="@impossiblechess" />
          <meta name="twitter:creator" content="@impossiblechess" />
          <meta property="og:url" content="http://impossiblechess.com" />
          <meta property="og:title" content="Impossible Chess" />
          <meta
            property="og:description"
            content="Can you beat the best bot in the world?"
          />
          <meta property="og:image" content="/impossible-chess-twitter.png" />
        </Helmet>
        <Header />
        <section className="chess">
          <div className="container">
            <StockFish>
              {({ position, onDrop, turns, history, gameOverStatus }) => (
                <>
                  <div className="chess__container">
                    <div className="chess__board">
                      <div className="chess__header">
                        <div className="chess__header__meta">
                          <span className="chess__gm"> GM </span>
                          <span className="chess__stockfish">
                            🤖 Impossiblebot
                          </span>
                          <span className="chess__rating">(3500)</span>
                          <div className="chess__header__turns">
                            <span className="silent">Turns: </span>
                            {turns}
                          </div>
                        </div>
                      </div>
                      <Chessboard
                        id="stockfish"
                        position={position}
                        width={600}
                        onDrop={onDrop}
                        boardStyle={boardStyle}
                        orientation="black"
                      />
                    </div>
                    <div className="chess__moves">
                      <div className="chess__moves__header">
                        <h3>Recent moves</h3>
                      </div>
                      <div className="chess__moves__list">
                        <ul>
                          {history.map((el, index) => (
                            <li key={index}>{el}</li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </div>

                  <Leaderboard />
                  <Welcome openStatus={"open"} />
                </>
              )}
            </StockFish>
          </div>
        </section>
        <Footer />
      </>
    );
  }
}

export default Game;

const boardsContainer = {
  display: "flex",
  justifyContent: "space-around",
  alignItems: "center",
};
const boardStyle = {
  borderRadius: "5px",
  boxShadow: `0 5px 15px rgba(0, 0, 0, 0.5)`,
};
