import Head from "next/head";
import Link from "next/link";
import { Chessboard } from "react-chessboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>About | Impossible Chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="hero">
        <div className="container">
          <h1>Impossible Chess</h1>
          <p>Can you beat the world's hardest chess bot?</p>
          <div className="hero__instructions">
            <h3>How to play</h3>
            <ol>
              <li>Type in a username</li>
              <li>
                See how long you can last against the world's hardest chess bot
              </li>
              <li>
                Once you get checkmated, check to see your position in the
                leaderboard
              </li>
            </ol>
          </div>
        </div>
      </section>
      <div className="chess__username">
        <div className="container">
          <div className="chess__username__meta">
            <input type="text" />
            <button className="chess__username__button">Begin</button>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
